### PR TITLE
Azure WAF Use DDoS Protection

### PR DESCRIPTION
**Pull request by markus-gsf-seidl**
#108 Use DDoS Protection

### CODE REVIEW

**Comment by greenhsu123** [comment]
Completed the initial review and the proposed pattern looks good! Thanks!

**Comment by markus-gsf-seidl** [comment]
LGTM

**Comment by russelltrow** [comment]
@markus-gsf-seidl sorry I merged this PR before I noticed it was against 'main' rather than 'dev'. Would you mind opening a new PR for this pattern against 'dev' please

**Comment by markus-gsf-seidl** [comment]
Will do!

**Pull request merged**
