### PR TITLE
Merge 'main' back into 'dev' so the branches are in sync

### PR DESCRIPTION
**Pull request by russelltrow**
The `dev` branch is currently behind `main` as some changes happened directly on `main`.

PR is to get them back in sync.

### CODE REVIEW

**Comment by russelltrow** [comment]
@greenhsu123 would you mind reviewing this for me please.

**Comment by markus-gsf-seidl** [comment]
I think all new patterns should go in `dev` and then, via a 2nd review which may be more like "adjust the language to english standards" to the `main` branch.

**Comment by russelltrow** [comment]
> I think all new patterns should go in `dev` and then, via a 2nd review which may be more like "adjust the language to english standards" to the `main` branch.

I agree, I have spoken with @catherinemaughan and she can help with the language review once a pattern is in Dev.

**Comment by markus-gsf-seidl** [comment]
This PR looks good to me @russelltrow

**Pull request merged**
