### PR TITLE
Issue #252: Extend pattern for choosing cloud region to include location-based carbon intensity

### PR DESCRIPTION
**Pull request by katerynao**
## Title
Choose the most efficient region based on proximity to user and carbon intensity

## Version
2.0

## Submitted By
kreuzwerker GmbH

## Published Date
29.09.2023

## Intent
From an energy-efficiency perspective, it's better to shorten the distance a network packet travels so that less energy is required to transmit it. Similarly, from an embodied-carbon perspective, when a network packet traverses through less computing equipment, we are more efficient with hardware.
In addition to that, it's also important to consider the carbon intensity of the physical location and choose the most balanced/sustainable region for your application workload based on both factors.

## Tags
```
---
tags:
 - cloud
 - networking
 - role:cloud-engineer
 - size:small
---
```

## Problem
From an energy-efficiency perspective, it's better to shorten the distance a network packet travels so that less energy is required to transmit it. Similarly, from an embodied-carbon perspective, when a network packet traverses through less computing equipment, we are more efficient with hardware.
In addition to that, it's also important to consider the carbon intensity of the physical location and choose the most balanced/sustainable region for your application workload based on both factors.

## Solution
Choose the most carbon efficient region closest to the majority of where the network packets are going.

## SCI Impact
```
`SCI = (E * I) + M per R`
```
Reducing the distance and the carbon intensity will impact SCI as follows:

- `E`: By reducing the distance a packet travels, less total electricity is required.
- `I`: By considering location-based marginal carbon emissions (gCO2/kWh), carbon intensity is reduced.
- `M`: By reducing the total number of computing equipment traversed, the total embodied carbon is lower.

## Assumptions
- Provided you have access to the carbon intensity data made available by the chosen cloud provider.
- Provided that your users are located relatively close to each other geographically.
- Provided that the necessary services for running your workload are accessible within the chosen region.

## Pros & Cons
- Costs: changing regions may increase or decrease the cost of running your workload, due to variation in prices of different services.
- Data protection: changing regions may require you to review your data protection policies and mechanisms based on local regulatory and compliance requirements.

### CODE REVIEW

**Comment by markus-gsf-seidl** [comment]
Initial review looks good, TLDR: It's an extension of the "Choose region closest to users" to adapt it to choose the most sustainable option instead "of going by distance" (as implied in the previous pattern)

**Comment by franziska-warncke** [comment]
I think it is ready for SME Review. @greenhsu123

**Review by markus-gsf-seidl — APPROVED** [review]
LGTM

**Comment by franziska-warncke** [comment]
I think we can close this, right? We do not want to mix up the patterns and leave it like they are now, right? :) @greenhsu123 @russelltrow

**Comment by greenhsu123** [comment]
Happy to have it close, thanks for the reviews.

**Pull request closed without merging**
